# Generated by Django 5.2.13 on 2026-04-27 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={'ordering': ['user__first_name']},
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custumer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='custumer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
